<?php
/**
 * @file
 * Module hooks implementations.
 */

use \Drupal\block_content\BlockContentInterface;

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add template suggestions block content types.
 */
function ila_block_base_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  $content = $variables['elements']['content'];
  if (isset($content['#block_content']) && $content['#block_content'] instanceof BlockContentInterface) {
    $suggestions[] = 'block__block_content_' . $content['#block_content']->bundle();
  }
}

/**
 * Implements hook_preprocess_block().
 *
 * Add bundle type class to content blocks.
 */
function ila_block_base_preprocess_block(&$variables) {
  if (isset($variables['content']['#block_content'])) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $variables['content']['#block_content'];
    $block_type = $block_content->bundle();

    $variables['attributes']['class'][] = "block-block-content-$block_type";
  }
}
