ila_registration.ila_registration_booth_type.*:
  type: config_entity
  label: 'Booth type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
