<?php

/**
 * @file
 * Contains ila_data_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ila_data_export_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ila_data_export module.
    case 'help.page.ila_data_export':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('ILA Data Export') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ila_data_export_theme($existing, $type, $theme, $path) {
  return [
    'summary_data_export' => [
      'variables' => [
        'content' => [],
      ],
    ],
  ];
}
